import { defineConfig } from "cypress";
import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild";

export default defineConfig({
  reporter: "node_modules/mochawesome/src/mochawesome.js",
  reporterOptions: {
    reportFilename: "Bbc Sport",
    reportPageTitle: "Complete Test Report",
    reportPageFooter: "<p>Generated by Mochawesome</p>",
    reportDirClean: true,
    reportDir: "reports",
    timestamp: "yyyy-mm-dd",
    consoleReporter: "spec",
    charts: true,
    code: true,
    cdn: false,
    overwrite: false,
    html: true,
    json: false,
    assertionStyle: "classic",
  },

  modifyObstructiveCode: false,
  video: true,
  videosFolder: "cypress/reports/videos",
  screenshotsFolder: "cypress/reports/screenshots",
  chromeWebSecurity: false,

  e2e: {
    specPattern: "cypress/e2e/bbcEditor.feature",
    supportFile: "cypress/support/e2e.ts",

    async setupNodeEvents(
      on: Cypress.PluginEvents,
      config: Cypress.PluginConfigOptions
    ) {
      // Enable Cucumber preprocessor
      await addCucumberPreprocessorPlugin(on, config);

      // Use ESBuild to compile TypeScript + feature files
      on(
        "file:preprocessor",
        createBundler({
          plugins: [createEsbuildPlugin(config)],
        })
      );

      // Return the modified Cypress config
      return config;
    },
  },
});
